#!/bin/bash

# Color modes.
fg() { echo "\[\e[3$1m\]"; }
bg() { echo "\[\e[4$1m\]"; }
bd() { echo "\[\e[1m\]"; }
nm() { echo "\[\e[m\]"; }


# Powerline glyphs.
# Format: {l(eft)/r(right)}{f(ull)/h(ollow) or u(p)/d(own) for triangle}{d(ivider)/t(riangle)/c(ircle)}
#lfd='\ue0b0'
#lhd='\ue0b1'
#rfd'\ue0b2'
#rhd'\ue0b3'
#ldt'\ue0b8'
#rdt'\ue0ba'
#rdt'\ue0bc'
#rut'\ue0be'
#lfc'\ue0b6'
#lhc'\ue0b7'
#rfc'\ue0b4'
#rhc'\ue0b5'

uh="$(fg 6)\u$(fg 9)@$(fg 6)\h$(fg 4)"

dir=$(realpath --relative-to ~/ $(pwd))
# If outside of the home dir.
if [ ${dir:0:2} = ".." ]; then
		echo "$uh \W$(fg 9) \$$(nm) "
# If inside the home dir.
else
	repo_info="$(git rev-parse --git-dir --is-inside-git-dir \
		--is-bare-repository --is-inside-work-tree --show-ref-format \
		--short HEAD 2>/dev/null)"
	if [[ -z "$repo_info" ]]; then
		echo "$uh $(fg 0)$(bg 4)$(fg 9) \W $(fg 4)$(bg 0)$(nm)"
	else
		branch="$(git branch | sed -n 's/^\* //p')"
		echo "$uh $(fg 0)$(bg 4)$(fg 9) \W $(fg 4)$(bg 3)$(fg 0) $branch $(fg 3)$(bg 0)$(nm)"
	fi
fi
